### ISSUE TITLE
Switch to uglify-js2

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/assets-packager#15]

**Comment by johnvuko** [comment]
I have almost done, i just have a problem with a test with the lineBreakAt options. I think it might be a regression on uglify-js2, i opened a ticket, i'm waiting...

**Comment by GoalSmashers** [comment]
Great! Please keep us updated.

**Comment by GoalSmashers** [comment]
@jonathantribouharet seems like there are no news on the issue your reported upstream: https://github.com/mishoo/UglifyJS2/issues/304

**Comment by GoalSmashers** [comment]
Fixed in 6962e4a89252a7a9f61abf591b3393e4f95aa9d8

Line breaks are "emulated" using `max_line_len` option as `width` option is not handled properly.

**Comment by XhmikosR** [comment]
Thanks! I'll check it out with the next npm package :+1:
