### ISSUE TITLE
error during test

### ISSUE THREAD

**Issue by qasimalyas** [jakubpawlowicz/assets-packager#3]
While i was going through the instructions to running the  `assetspkg -c assets.yml -g` command, it is returning the following error `-bash: assetspkg: command not found`. I didn't get any errors during the install of assets-packager and i'm running 0.6.12 version of node.

**Comment by GoalSmashers** [comment]
Hi Qasim,

There's a bug in the docs as it assumes assets-packager is installed globally:

```
npm install -g assets-packager
```

You can also run it from examples via:

```
../bin/assetspkg -c assets.yml -g
```

Just updated the docs.
