### ISSUE TITLE
upgrading issue and config question

### ISSUE THREAD

**Issue by qasimalyas** [jakubpawlowicz/assets-packager#9]
I have two items which i hope you can help with:
1. I'm trying to upgrade from 0.4.2 to the latest 0.7.0 and am unable to. I ran the `npm update assets-packager` command which was successful but upon checking the version `assetspkg --version` I still get 0.4.2. Any thoughts on what is happening here?
2. Is it possible to change the output paths (public, javascript and stylesheets) to something else? If it's possible then would this be set in the assets.yml file. Would you also be kind enough to give an example of this?

Thanks

**Comment by GoalSmashers** [comment]
Hi @kas187,

Ad 1) If you have assets-packager installed globally (and it seems to me you do) then please try 'npm update -g assets-packager'. This should help.
Ad 2) Although you can configure location of `public` directory (via -r option) there is no way to change `javascripts`, and `stylesheets` paths. Could you give us your use case so we can better understand what you are trying to acomplish and possibly patch assets-packager?

Thanks,
Jakub

**Comment by qasimalyas** [comment]
Thanks Jakub for the quick response.
1. The `npm update -g assets-packager` worked! Thanks.
2. I think what I was trying to get at was mainly the naming. It would've been nice if I could rename / set stylesheets to be **css** and javascripts to be **scripts**. Not really a deal breaker but would've been nice to set those. 

I do have a request for you. It would be nice to have a flag to optionally run [bless](http://blesscss.com/) on stylesheets. I've personally worked on massive projects and this has been invaluable. I could see this being useful here too.

**Comment by GoalSmashers** [comment]
You are welcome, @kas187.

We're adding #2 as an issue.
Interesting idea about `bless` - let me check if it's possible to integrate it into asset-packager. Is it something you would like to use at your current project too?

**Comment by qasimalyas** [comment]
Well at work we have an internal build packager so we can't really use assets-packager there but for all my personal projects I don't see any reason not to use it. TBH I don't think my current project would hit the selector limit as that is only a problem in IE8 and below. My personal projects would be too small to hit that limit.

**Comment by GoalSmashers** [comment]
Great. Thanks for sharing your use case with us.

So let's add the configurable css/js directories first and leave `bless` for some later time since it's not immediately needed. We will try to squeeze the former one into this week.

**Comment by GoalSmashers** [comment]
Hi Qasim,

We've just released assets-packager 0.8 which brings JS/CSS path configuration.

Simply pass `--pj/--js-path` or `--ps/--styles-path` option to configure JS and CSS respectively.
E.g. `assetspkg -r ./public -c assets.yml --js-path ./js --styles-path ./css` to use `public/js` for JS and `public/css` for CSS.

Enjoy!

**Comment by qasimalyas** [comment]
Sweet! Thanks for this.

**Comment by GoalSmashers** [comment]
You are welcome!
